Testing further ...

diff --git a/.buildkite/pipeline.yml b/.buildkite/pipeline.yml
--- a/.buildkite/pipeline.yml
+++ b/.buildkite/pipeline.yml
@@ -7,11 +7,11 @@ steps:
     command: |
       echo "Running main task"
       echo "This step will fail for testing"
-      exit 1  # Force failure
-
-  - wait
-
+      exit 1  # Force failure 
   - label: "Check Step 1 and Upload Conditional Step"
+    depends_on: step1
+    key: "step2"
+    allow_dependency_failure: true
     command: |
       if [ "$(buildkite-agent step get "outcome" --step "step1")" == "failed" ] || [ "$(buildkite-agent step get "outcome" --step "step1")" == "hard_failed" ]; then
         echo "Step 1 failed! Uploading fallback step..."
